import Header from "@/components/header";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import dynamic from "next/dynamic";
// 远程获取谷歌字体 需要外网不推荐
// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
import { Providers } from "./Providers";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const Header = dynamic(() => import("@/components/header"), {
  //   ssr: false,
  // });
  return (
    <html lang="en">
      {/* className={inter.className} */}
      <body>
        <Providers>
          <Header />
          <div className="c1ontainer mx-auto px-48">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
